ER-1197: Swap “description from publisher” and “description from DBC”
eReolen/base pull request #194
Opened 2021-10-07 15:36 UTC by rimi-itk

https://jira.itkdev.dk/browse/ER-1197

2021-10-07 20:52 UTC, cableman requested changes

2021-10-07 20:52 UTC, cableman commented on sites/all/themes/orwell/assets/sass/component/_ting-object.scss
> +    // padding-bottom: 40px;
Comment out code?

2021-10-07 20:52 UTC, cableman commented on sites/all/themes/orwell/assets/sass/component/_ting-object.scss
> +      // padding: 2rem 0;
Comment out code?

2021-10-07 20:52 UTC, cableman commented on sites/all/themes/orwell/assets/sass/component/_ting-object.scss
> +    // padding: 1.5rem 0;
Comment out code?

2021-10-12 08:16 UTC, rimi-itk commented on sites/all/themes/orwell/assets/sass/component/_ting-object.scss
> +    // padding: 1.5rem 0;
Fixed.

2021-10-12 11:20 UTC, merged