Initial shot at showing square covers in carusels
eReolen/base pull request #297
Opened 2023-04-24 06:03 UTC by yepzdk

#### Link to ticket

https://jira.itkdev.dk/browse/ER-1361

#### Description

Change carrusel to accommodate square covers.

#### Screenshot of the result

<img width="1165" alt="Screenshot 2023-04-24 at 08 01 40" src="https://user-images.githubusercontent.com/332915/233912017-2752c72d-9c9f-4102-a635-c191655d8218.png">

#### Checklist

- [ ] My code passes our static analysis suite.
- [ ] My code passes our continuous integration process.

If your code does not pass all the requirements on the checklist you have to add a comment explaining why this change
should be exempt from the list.

#### Additional comments or questions

If you have any further comments or questions for the reviewer please add them here.

2023-05-01 11:00 UTC, rimi-itk requested changes

2023-05-01 11:00 UTC, rimi-itk commented on sites/all/themes/orwell/assets/sass/component/_carousel.scss
> +  // }
Remove these lines if they're not needed.

2023-05-02 08:32 UTC, rimi-itk approved these changes

2023-05-11 11:21 UTC, yepzdk commented
Updated with code for eReolenGO

2023-05-12 07:50 UTC, rimi-itk approved these changes

2023-05-12 07:50 UTC, rimi-itk commented on sites/all/themes/orwell/assets/sass/component/_carousel.scss
> +// The following has been taken from ding_carousel.css. This avoids load jumping.
🎉

2023-05-22 08:23 UTC, merged